//go:build legacy_types

// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type DetailAccountRequest struct {
	Id    string `json:"id,optional"`
	Email string `json:"email,optional"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token     string `json:"token"`
	Id        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Nickname  string `json:"nickname"`
	AvatarUrl string `json:"avatarUrl"`
	Bio       string `json:"bio"`
	Status    string `json:"status"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type RegisterRequest struct {
	Username      string `json:"username,optional"`
	Email         string `json:"email"`
	Password      string `json:"password"`
	CheckPassword string `json:"checkPassword"`
}

type RegisterResponse struct {
	Id string `json:"id"`
}

type UpdateAccountRequest struct {
	Id        string `json:"id"`
	Username  string `json:"username,optional"`
	Email     string `json:"email,optional"`
	Password  string `json:"password,optional"`
	Nickname  string `json:"nickname,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
	Bio       string `json:"bio,optional"`
}
