// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AdminQueryMediaAssetRequest struct {
	Id            string              `json:"id,optional"`
	Title         string              `json:"title,optional"`
	Category      string              `json:"category,optional"`
	AuditStatus   string              `json:"auditStatus,default=pending"`
	Tags          []string            `json:"tags,optional"`
	FileSize      int64               `json:"fileSize,optional"`
	Width         int64               `json:"width,optional"`
	Height        int64               `json:"height,optional"`
	AspectRatio   float64             `json:"aspectRatio,optional"`
	FileExt       string              `json:"fileExt,optional"`
	OwnerUserId   string              `json:"ownerUserId,optional"`
	SearchText    string              `json:"searchText,optional"`
	CreatedAtFrom string              `json:"createdAtFrom,optional"`
	CreatedAtTo   string              `json:"createdAtTo,optional"`
	Variant       MediaVariantRequest `json:"variantOption,optional"`
	PageNum       int64               `json:"pageNum,optional"`
	PageSize      int64               `json:"pageSize,optional"`
}

type AdminUpdateAccountRequest struct {
	Id        string `json:"id"`
	Username  string `json:"username,optional"`
	Email     string `json:"email,optional"`
	Password  string `json:"password,optional"`
	Nickname  string `json:"nickname,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
	Bio       string `json:"bio,optional"`
	Status    string `json:"status,optional"`
}
