//go:build legacy_types

// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CursorQueryMediaAssetRequest struct {
	Id            string              `json:"id,optional"`
	Title         string              `json:"title,optional"`
	Category      string              `json:"category,optional"`
	Tags          []string            `json:"tags,optional"`
	FileSize      int64               `json:"fileSize,optional"`
	Width         int64               `json:"width,optional"`
	Height        int64               `json:"height,optional"`
	AspectRatio   float64             `json:"aspectRatio,optional"`
	FileExt       string              `json:"fileExt,optional"`
	OwnerUserId   string              `json:"ownerUserId,optional"`
	SearchText    string              `json:"searchText,optional"`
	CreatedAtFrom string              `json:"createdAtFrom,optional"`
	CreatedAtTo   string              `json:"createdAtTo,optional"`
	Variant       MediaVariantRequest `json:"variantOption,optional"`
	Cursor        string              `json:"cursor,optional"`
	PageSize      int64               `json:"pageSize,optional"`
}

type DeleteMediaAssetRequest struct {
	Id    string `json:"id"`
	Force bool   `json:"force,optional"`
}

type GetMediaAssetRequest struct {
	Id      string              `json:"id"`
	Variant MediaVariantRequest `json:"variantOption,optional"`
}

type MediaAssetCursorPageResponse struct {
	PageSize   int64                `json:"pageSize"`
	HasMore    bool                 `json:"hasMore"`
	NextCursor string               `json:"nextCursor"`
	List       []MediaAssetResponse `json:"list"`
}

type MediaAssetResponse struct {
	Id               string                `json:"id"`
	MediaType        string                `json:"mediaType"`
	AssetUsage       string                `json:"assetUsage"`
	Title            string                `json:"title"`
	Description      string                `json:"description"`
	Category         string                `json:"category"`
	Tags             []string              `json:"tags"`
	OwnerUserId      string                `json:"ownerUserId"`
	Owner            AccountSummary        `json:"owner"`
	OriginalFilename string                `json:"originalFilename"`
	Visibility       string                `json:"visibility"`
	Status           string                `json:"status"`
	AuditStatus      string                `json:"auditStatus"`
	ReviewMessage    string                `json:"reviewMessage,omitempty"`
	ReviewerId       string                `json:"reviewerId,omitempty"`
	ReviewTime       string                `json:"reviewTime,omitempty"`
	FileSize         int64                 `json:"fileSize"`
	Width            int64                 `json:"width"`
	Height           int64                 `json:"height"`
	AspectRatio      float64               `json:"aspectRatio"`
	MimeType         string                `json:"mimeType"`
	FileExt          string                `json:"fileExt"`
	DominantColor    string                `json:"dominantColor"`
	BlurHash         string                `json:"blurHash"`
	Urls             MediaAssetUrls        `json:"urls"`
	Permissions      MediaAssetPermissions `json:"permissions"`
	Stats            MediaAssetStats       `json:"stats"`
	MetadataJson     string                `json:"metadataJson,omitempty"`
	CreatedAt        string                `json:"createdAt"`
	UpdatedAt        string                `json:"updatedAt"`
}

type QueryMediaAssetRequest struct {
	Id            string              `json:"id,optional"`
	Title         string              `json:"title,optional"`
	Category      string              `json:"category,optional"`
	Tags          []string            `json:"tags,optional"`
	FileSize      int64               `json:"fileSize,optional"`
	Width         int64               `json:"width,optional"`
	Height        int64               `json:"height,optional"`
	AspectRatio   float64             `json:"aspectRatio,optional"`
	FileExt       string              `json:"fileExt,optional"`
	OwnerUserId   string              `json:"ownerUserId,optional"`
	SearchText    string              `json:"searchText,optional"`
	CreatedAtFrom string              `json:"createdAtFrom,optional"`
	CreatedAtTo   string              `json:"createdAtTo,optional"`
	Variant       MediaVariantRequest `json:"variantOption,optional"`
	PageNum       int64               `json:"pageNum,optional"`
	PageSize      int64               `json:"pageSize,optional"`
}

type ReviewMediaAssetRequest struct {
	Id            string `json:"id"`
	AuditStatus   string `json:"auditStatus"`
	ReviewMessage string `json:"reviewMessage,optional"`
}
