// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type OverviewStatsResponse struct {
	PublicMediaAssetCount int64 `json:"publicMediaAssetCount"`
	CreatorCount          int64 `json:"creatorCount"`
	PublicPostCount       int64 `json:"publicPostCount"`
	PublicAlbumCount      int64 `json:"publicAlbumCount"`
}
