// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ProfileAlbumListRequest struct {
	UserId   string `json:"userId,optional"`
	PageNum  int64  `json:"pageNum,optional"`
	PageSize int64  `json:"pageSize,optional"`
}

type ProfileAlbumPageResponse struct {
	PageNum  int64                  `json:"pageNum"`
	PageSize int64                  `json:"pageSize"`
	Total    int64                  `json:"total"`
	List     []ProfileAlbumResponse `json:"list"`
}

type ProfileFeaturedMediaListRequest struct {
	UserId   string              `json:"userId,optional"`
	PageSize int64               `json:"pageSize,optional"`
	Variant  MediaVariantRequest `json:"variantOption,optional"`
}

type UpdateProfileFeaturedMediaRequest struct {
	MediaAssetIds []string `json:"mediaAssetIds,optional"`
}

type ProfilePostCursorPageResponse struct {
	PageSize   int64                 `json:"pageSize"`
	HasMore    bool                  `json:"hasMore"`
	NextCursor string                `json:"nextCursor"`
	List       []ProfilePostResponse `json:"list"`
}

type ProfilePostListRequest struct {
	UserId   string `json:"userId,optional"`
	Cursor   string `json:"cursor,optional"`
	PageSize int64  `json:"pageSize,optional"`
}
