// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AccountSummary struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Nickname  string `json:"nickname"`
	AvatarUrl string `json:"avatarUrl"`
	Bio       string `json:"bio"`
	Status    string `json:"status"`
	Role      string `json:"role"`
}

type DetailAccountResponse struct {
	Id                      string `json:"id"`
	Username                string `json:"username"`
	Email                   string `json:"email"`
	Phone                   string `json:"phone"`
	Nickname                string `json:"nickname"`
	AvatarUrl               string `json:"avatarUrl"`
	Bio                     string `json:"bio"`
	Status                  string `json:"status"`
	Role                    string `json:"role"`
	CreatedAt               string `json:"createdAt"`
	UpdatedAt               string `json:"updatedAt"`
	MediaAssetCount         int64  `json:"mediaAssetCount"`
	PublicMediaAssetCount   int64  `json:"publicMediaAssetCount"`
	ApprovedMediaAssetCount int64  `json:"approvedMediaAssetCount"`
	PendingMediaAssetCount  int64  `json:"pendingMediaAssetCount"`
	RejectedMediaAssetCount int64  `json:"rejectedMediaAssetCount"`
}

type MediaAssetPageResponse struct {
	PageNum  int64                `json:"pageNum"`
	PageSize int64                `json:"pageSize"`
	Total    int64                `json:"total"`
	List     []MediaAssetResponse `json:"list"`
}

type MediaAssetPermissions struct {
	CanViewOriginal bool `json:"canViewOriginal"`
	CanDownload     bool `json:"canDownload"`
}

type MediaAssetStats struct {
	ViewCount     int64 `json:"viewCount"`
	ReactionCount int64 `json:"reactionCount"`
	FavoriteCount int64 `json:"favoriteCount"`
	CommentCount  int64 `json:"commentCount"`
	ShareCount    int64 `json:"shareCount"`
	DownloadCount int64 `json:"downloadCount"`
}

type MediaAssetUrls struct {
	Thumbnail string `json:"thumbnail"`
	Preview   string `json:"preview"`
	Detail    string `json:"detail"`
	Original  string `json:"original"`
}

type MediaVariantRequest struct {
	Variant      string `json:"variant,optional"`
	CompressType int64  `json:"compressType,default=0"`
	CutWidth     int64  `json:"cutWidth,optional"`
	CutHeight    int64  `json:"cutHeight,optional"`
}

type ProfileAlbumResponse struct {
	Id          string             `json:"id"`
	UserId      string             `json:"userId"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Cover       MediaAssetResponse `json:"cover"`
	ItemCount   int64              `json:"itemCount"`
	Visibility  string             `json:"visibility"`
	Status      string             `json:"status"`
	CreatedAt   string             `json:"createdAt"`
	UpdatedAt   string             `json:"updatedAt"`
}

type ProfilePostResponse struct {
	Id          string               `json:"id"`
	UserId      string               `json:"userId"`
	Content     string               `json:"content"`
	Visibility  string               `json:"visibility"`
	Status      string               `json:"status"`
	Location    string               `json:"location"`
	IsPinned    bool                 `json:"isPinned"`
	PinnedAt    string               `json:"pinnedAt"`
	Images      []MediaAssetResponse `json:"images"`
	Stats       MediaAssetStats      `json:"stats"`
	IsLiked     bool                 `json:"isLiked"`
	IsFavorited bool                 `json:"isFavorited"`
	CreatedAt   string               `json:"createdAt"`
	UpdatedAt   string               `json:"updatedAt"`
}
