// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentRecordFieldNames          = builder.RawFieldNames(&CommentRecord{})
	commentRecordRows                = strings.Join(commentRecordFieldNames, ",")
	commentRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(commentRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(commentRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	commentRecordModel interface {
		Insert(ctx context.Context, data *CommentRecord) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommentRecord, error)
		Update(ctx context.Context, data *CommentRecord) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommentRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CommentRecord struct {
		Id         uint64        `db:"id"`          // 评论ID
		UserId     uint64        `db:"user_id"`     // 评论用户ID
		TargetType string        `db:"target_type"` // 目标类型：post / media_asset / album
		TargetId   uint64        `db:"target_id"`   // 目标对象ID
		ParentId   sql.NullInt64 `db:"parent_id"`   // 父评论ID，用于回复
		RootId     sql.NullInt64 `db:"root_id"`     // 根评论ID，方便查询评论树
		Content    string        `db:"content"`     // 评论内容
		Status     string        `db:"status"`      // 状态：active正常 / hidden隐藏 / deleted已删除
		CreatedAt  time.Time     `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time     `db:"updated_at"`  // 更新时间
		DeletedAt  sql.NullTime  `db:"deleted_at"`  // 软删除时间
	}
)

func newCommentRecordModel(conn sqlx.SqlConn) *defaultCommentRecordModel {
	return &defaultCommentRecordModel{
		conn:  conn,
		table: "`comment_record`",
	}
}

func (m *defaultCommentRecordModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommentRecordModel) FindOne(ctx context.Context, id uint64) (*CommentRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentRecordRows, m.table)
	var resp CommentRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentRecordModel) Insert(ctx context.Context, data *CommentRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, commentRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TargetType, data.TargetId, data.ParentId, data.RootId, data.Content, data.Status, data.DeletedAt)
	return ret, err
}

func (m *defaultCommentRecordModel) Update(ctx context.Context, data *CommentRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TargetType, data.TargetId, data.ParentId, data.RootId, data.Content, data.Status, data.DeletedAt, data.Id)
	return err
}

func (m *defaultCommentRecordModel) tableName() string {
	return m.table
}
