// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	entityStatFieldNames          = builder.RawFieldNames(&EntityStat{})
	entityStatRows                = strings.Join(entityStatFieldNames, ",")
	entityStatRowsExpectAutoSet   = strings.Join(stringx.Remove(entityStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	entityStatRowsWithPlaceHolder = strings.Join(stringx.Remove(entityStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	entityStatModel interface {
		Insert(ctx context.Context, data *EntityStat) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*EntityStat, error)
		FindOneByTargetTypeTargetId(ctx context.Context, targetType string, targetId uint64) (*EntityStat, error)
		Update(ctx context.Context, data *EntityStat) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultEntityStatModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EntityStat struct {
		Id            uint64    `db:"id"`             // 统计ID
		TargetType    string    `db:"target_type"`    // 目标类型：media_asset / post / album / comment_record / user_profile
		TargetId      uint64    `db:"target_id"`      // 目标对象ID
		ViewCount     uint64    `db:"view_count"`     // 浏览数
		ReactionCount uint64    `db:"reaction_count"` // 互动数，如点赞数
		FavoriteCount uint64    `db:"favorite_count"` // 收藏数
		CommentCount  uint64    `db:"comment_count"`  // 评论数
		ShareCount    uint64    `db:"share_count"`    // 分享数
		DownloadCount uint64    `db:"download_count"` // 下载数
		CreatedAt     time.Time `db:"created_at"`     // 创建时间
		UpdatedAt     time.Time `db:"updated_at"`     // 更新时间
	}
)

func newEntityStatModel(conn sqlx.SqlConn) *defaultEntityStatModel {
	return &defaultEntityStatModel{
		conn:  conn,
		table: "`entity_stat`",
	}
}

func (m *defaultEntityStatModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEntityStatModel) FindOne(ctx context.Context, id uint64) (*EntityStat, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", entityStatRows, m.table)
	var resp EntityStat
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEntityStatModel) FindOneByTargetTypeTargetId(ctx context.Context, targetType string, targetId uint64) (*EntityStat, error) {
	var resp EntityStat
	query := fmt.Sprintf("select %s from %s where `target_type` = ? and `target_id` = ? limit 1", entityStatRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, targetType, targetId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEntityStatModel) Insert(ctx context.Context, data *EntityStat) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, entityStatRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TargetType, data.TargetId, data.ViewCount, data.ReactionCount, data.FavoriteCount, data.CommentCount, data.ShareCount, data.DownloadCount)
	return ret, err
}

func (m *defaultEntityStatModel) Update(ctx context.Context, newData *EntityStat) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, entityStatRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TargetType, newData.TargetId, newData.ViewCount, newData.ReactionCount, newData.FavoriteCount, newData.CommentCount, newData.ShareCount, newData.DownloadCount, newData.Id)
	return err
}

func (m *defaultEntityStatModel) tableName() string {
	return m.table
}
