// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaAssetFieldNames          = builder.RawFieldNames(&MediaAsset{})
	mediaAssetRows                = strings.Join(mediaAssetFieldNames, ",")
	mediaAssetRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaAssetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaAssetRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaAssetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	mediaAssetModel interface {
		Insert(ctx context.Context, data *MediaAsset) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MediaAsset, error)
		Update(ctx context.Context, data *MediaAsset) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMediaAssetModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MediaAsset struct {
		Id               uint64         `db:"id"`                // 媒体资源ID
		OwnerUserId      uint64         `db:"owner_user_id"`     // 上传者/所有者用户ID
		MediaType        string         `db:"media_type"`        // 媒体类型：image / video / audio / document
		AssetUsage       string         `db:"asset_usage"`       // 业务用途：work作品 / post动态附件 / avatar头像 / temp临时
		Title            sql.NullString `db:"title"`             // 标题
		Description      sql.NullString `db:"description"`       // 描述
		OriginalFilename sql.NullString `db:"original_filename"` // 原始文件名
		Visibility       string         `db:"visibility"`        // 可见性：public公开 / private私有 / followers粉丝可见 / unlisted不公开但可访问
		Status           string         `db:"status"`            // 资源状态：uploading上传中 / processing处理中 / active正常 / failed失败 / deleted已删除
		AuditStatus      string         `db:"audit_status"`      // 审核状态：pending待审核 / approved通过 / rejected拒绝
		MetadataJson     sql.NullString `db:"metadata_json"`     // 扩展元数据，如 EXIF、AI标签、拍摄设备、地点等
		CreatedAt        time.Time      `db:"created_at"`        // 创建时间
		UpdatedAt        time.Time      `db:"updated_at"`        // 更新时间
		DeletedAt        sql.NullTime   `db:"deleted_at"`        // 软删除时间
	}
)

func newMediaAssetModel(conn sqlx.SqlConn) *defaultMediaAssetModel {
	return &defaultMediaAssetModel{
		conn:  conn,
		table: "`media_asset`",
	}
}

func (m *defaultMediaAssetModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMediaAssetModel) FindOne(ctx context.Context, id uint64) (*MediaAsset, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaAssetRows, m.table)
	var resp MediaAsset
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaAssetModel) Insert(ctx context.Context, data *MediaAsset) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mediaAssetRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OwnerUserId, data.MediaType, data.AssetUsage, data.Title, data.Description, data.OriginalFilename, data.Visibility, data.Status, data.AuditStatus, data.MetadataJson, data.DeletedAt)
	return ret, err
}

func (m *defaultMediaAssetModel) Update(ctx context.Context, data *MediaAsset) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mediaAssetRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OwnerUserId, data.MediaType, data.AssetUsage, data.Title, data.Description, data.OriginalFilename, data.Visibility, data.Status, data.AuditStatus, data.MetadataJson, data.DeletedAt, data.Id)
	return err
}

func (m *defaultMediaAssetModel) tableName() string {
	return m.table
}
