// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reactionFieldNames          = builder.RawFieldNames(&Reaction{})
	reactionRows                = strings.Join(reactionFieldNames, ",")
	reactionRowsExpectAutoSet   = strings.Join(stringx.Remove(reactionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reactionRowsWithPlaceHolder = strings.Join(stringx.Remove(reactionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	reactionModel interface {
		Insert(ctx context.Context, data *Reaction) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Reaction, error)
		FindOneByUserIdTargetTypeTargetIdReactionType(ctx context.Context, userId uint64, targetType string, targetId uint64, reactionType string) (*Reaction, error)
		Update(ctx context.Context, data *Reaction) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultReactionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Reaction struct {
		Id           uint64    `db:"id"`            // 互动ID
		UserId       uint64    `db:"user_id"`       // 操作用户ID
		TargetType   string    `db:"target_type"`   // 目标类型：post / media_asset / comment_record / album
		TargetId     uint64    `db:"target_id"`     // 目标对象ID
		ReactionType string    `db:"reaction_type"` // 互动类型：like点赞 / love爱心 / clap鼓掌 / wow惊喜
		Status       int64     `db:"status"`        // 状态：1有效 / 0取消
		CreatedAt    time.Time `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`    // 更新时间
	}
)

func newReactionModel(conn sqlx.SqlConn) *defaultReactionModel {
	return &defaultReactionModel{
		conn:  conn,
		table: "`reaction`",
	}
}

func (m *defaultReactionModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultReactionModel) FindOne(ctx context.Context, id uint64) (*Reaction, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reactionRows, m.table)
	var resp Reaction
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReactionModel) FindOneByUserIdTargetTypeTargetIdReactionType(ctx context.Context, userId uint64, targetType string, targetId uint64, reactionType string) (*Reaction, error) {
	var resp Reaction
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `target_type` = ? and `target_id` = ? and `reaction_type` = ? limit 1", reactionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, targetType, targetId, reactionType)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReactionModel) Insert(ctx context.Context, data *Reaction) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, reactionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TargetType, data.TargetId, data.ReactionType, data.Status)
	return ret, err
}

func (m *defaultReactionModel) Update(ctx context.Context, newData *Reaction) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, reactionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.TargetType, newData.TargetId, newData.ReactionType, newData.Status, newData.Id)
	return err
}

func (m *defaultReactionModel) tableName() string {
	return m.table
}
