// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taggingFieldNames          = builder.RawFieldNames(&Tagging{})
	taggingRows                = strings.Join(taggingFieldNames, ",")
	taggingRowsExpectAutoSet   = strings.Join(stringx.Remove(taggingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	taggingRowsWithPlaceHolder = strings.Join(stringx.Remove(taggingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	taggingModel interface {
		Insert(ctx context.Context, data *Tagging) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Tagging, error)
		FindOneByTagIdTargetTypeTargetId(ctx context.Context, tagId uint64, targetType string, targetId uint64) (*Tagging, error)
		Update(ctx context.Context, data *Tagging) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTaggingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Tagging struct {
		Id         uint64          `db:"id"`          // 标签关联ID
		TagId      uint64          `db:"tag_id"`      // 标签ID
		TargetType string          `db:"target_type"` // 目标类型：media_asset / post / album / user_profile
		TargetId   uint64          `db:"target_id"`   // 目标对象ID
		Source     string          `db:"source"`      // 标签来源：user用户 / system系统 / ai机器生成
		Confidence sql.NullFloat64 `db:"confidence"`  // AI标签置信度，范围0-1
		CreatedAt  time.Time       `db:"created_at"`  // 创建时间
	}
)

func newTaggingModel(conn sqlx.SqlConn) *defaultTaggingModel {
	return &defaultTaggingModel{
		conn:  conn,
		table: "`tagging`",
	}
}

func (m *defaultTaggingModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTaggingModel) FindOne(ctx context.Context, id uint64) (*Tagging, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taggingRows, m.table)
	var resp Tagging
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaggingModel) FindOneByTagIdTargetTypeTargetId(ctx context.Context, tagId uint64, targetType string, targetId uint64) (*Tagging, error) {
	var resp Tagging
	query := fmt.Sprintf("select %s from %s where `tag_id` = ? and `target_type` = ? and `target_id` = ? limit 1", taggingRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tagId, targetType, targetId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaggingModel) Insert(ctx context.Context, data *Tagging) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, taggingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TagId, data.TargetType, data.TargetId, data.Source, data.Confidence)
	return ret, err
}

func (m *defaultTaggingModel) Update(ctx context.Context, newData *Tagging) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taggingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TagId, newData.TargetType, newData.TargetId, newData.Source, newData.Confidence, newData.Id)
	return err
}

func (m *defaultTaggingModel) tableName() string {
	return m.table
}
