// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFollowFieldNames          = builder.RawFieldNames(&UserFollow{})
	userFollowRows                = strings.Join(userFollowFieldNames, ",")
	userFollowRowsExpectAutoSet   = strings.Join(stringx.Remove(userFollowFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userFollowRowsWithPlaceHolder = strings.Join(stringx.Remove(userFollowFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userFollowModel interface {
		Insert(ctx context.Context, data *UserFollow) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserFollow, error)
		FindOneByFollowerIdFollowingId(ctx context.Context, followerId uint64, followingId uint64) (*UserFollow, error)
		Update(ctx context.Context, data *UserFollow) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserFollowModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserFollow struct {
		Id          uint64    `db:"id"`           // 关注关系ID
		FollowerId  uint64    `db:"follower_id"`  // 关注者用户ID
		FollowingId uint64    `db:"following_id"` // 被关注者用户ID
		Status      int64     `db:"status"`       // 状态：1关注 / 0取消关注
		CreatedAt   time.Time `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time `db:"updated_at"`   // 更新时间
	}
)

func newUserFollowModel(conn sqlx.SqlConn) *defaultUserFollowModel {
	return &defaultUserFollowModel{
		conn:  conn,
		table: "`user_follow`",
	}
}

func (m *defaultUserFollowModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserFollowModel) FindOne(ctx context.Context, id uint64) (*UserFollow, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFollowRows, m.table)
	var resp UserFollow
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFollowModel) FindOneByFollowerIdFollowingId(ctx context.Context, followerId uint64, followingId uint64) (*UserFollow, error) {
	var resp UserFollow
	query := fmt.Sprintf("select %s from %s where `follower_id` = ? and `following_id` = ? limit 1", userFollowRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, followerId, followingId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFollowModel) Insert(ctx context.Context, data *UserFollow) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userFollowRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.FollowerId, data.FollowingId, data.Status)
	return ret, err
}

func (m *defaultUserFollowModel) Update(ctx context.Context, newData *UserFollow) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userFollowRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.FollowerId, newData.FollowingId, newData.Status, newData.Id)
	return err
}

func (m *defaultUserFollowModel) tableName() string {
	return m.table
}
