// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAccountFieldNames          = builder.RawFieldNames(&UserAccount{})
	userAccountRows                = strings.Join(userAccountFieldNames, ",")
	userAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(userAccountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAccountRowsWithPlaceHolder = strings.Join(stringx.Remove(userAccountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAccountModel interface {
		Insert(ctx context.Context, data *UserAccount) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAccount, error)
		FindOneByEmail(ctx context.Context, email sql.NullString) (*UserAccount, error)
		FindOneByPhone(ctx context.Context, phone sql.NullString) (*UserAccount, error)
		FindOneByUsername(ctx context.Context, username string) (*UserAccount, error)
		Update(ctx context.Context, data *UserAccount) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAccount struct {
		Id           uint64         `db:"id"`            // 用户ID
		Username     string         `db:"username"`      // 用户名，系统内唯一
		Email        sql.NullString `db:"email"`         // 邮箱，可用于登录
		Phone        sql.NullString `db:"phone"`         // 手机号，可用于登录
		PasswordHash sql.NullString `db:"password_hash"` // 密码哈希，不存明文密码
		Status       string         `db:"status"`        // 账号状态：active正常 / disabled禁用 / deleted已删除
		LastLoginAt  sql.NullTime   `db:"last_login_at"` // 最后登录时间
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
		DeletedAt    sql.NullTime   `db:"deleted_at"`    // 软删除时间
	}
)

func newUserAccountModel(conn sqlx.SqlConn) *defaultUserAccountModel {
	return &defaultUserAccountModel{
		conn:  conn,
		table: "`user_account`",
	}
}

func (m *defaultUserAccountModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAccountModel) FindOne(ctx context.Context, id uint64) (*UserAccount, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAccountRows, m.table)
	var resp UserAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAccountModel) FindOneByEmail(ctx context.Context, email sql.NullString) (*UserAccount, error) {
	var resp UserAccount
	query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", userAccountRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAccountModel) FindOneByPhone(ctx context.Context, phone sql.NullString) (*UserAccount, error) {
	var resp UserAccount
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userAccountRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAccountModel) FindOneByUsername(ctx context.Context, username string) (*UserAccount, error) {
	var resp UserAccount
	query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", userAccountRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAccountModel) Insert(ctx context.Context, data *UserAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.Email, data.Phone, data.PasswordHash, data.Status, data.LastLoginAt, data.DeletedAt)
	return ret, err
}

func (m *defaultUserAccountModel) Update(ctx context.Context, newData *UserAccount) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAccountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Username, newData.Email, newData.Phone, newData.PasswordHash, newData.Status, newData.LastLoginAt, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultUserAccountModel) tableName() string {
	return m.table
}
