// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	account "discover_world/internal/handler/account"
	admin "discover_world/internal/handler/admin"
	homepage "discover_world/internal/handler/homepage"
	media "discover_world/internal/handler/media"
	overview "discover_world/internal/handler/overview"
	post "discover_world/internal/handler/post"
	profile "discover_world/internal/handler/profile"
	search "discover_world/internal/handler/search"
	"discover_world/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/login",
				Handler: account.LoginAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/register",
				Handler: account.RegisterAccountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/avatar/upload",
				Handler: account.UploadAccountAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/detail",
				Handler: account.DetailAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/update",
				Handler: account.UpdateAccountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/account/update",
					Handler: admin.AdminUpdateAccountHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/homepage/featured/update",
					Handler: admin.UpdateHomepageFeaturedHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/homepage/hero/update",
					Handler: admin.UpdateHomepageHeroHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/media/list",
					Handler: admin.GetAdminMediaAssetListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/homepage/config",
				Handler: homepage.GetHomepageConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: search.GlobalSearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/media/list",
				Handler: media.GetMediaAssetListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/list/cursor",
				Handler: media.GetMediaAssetCursorListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/media/delete",
				Handler: media.DeleteMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/detail",
				Handler: media.GetMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/upload",
				Handler: media.UploadMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/upload/url",
				Handler: media.UploadMediaAssetByUrlHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/media/review",
					Handler: media.ReviewMediaAssetHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/overview/stats",
				Handler: overview.GetOverviewStatsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/post/comment/create",
				Handler: post.CreatePostCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/comment/list/cursor",
				Handler: post.GetPostCommentCursorListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/create",
				Handler: post.CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/delete",
				Handler: post.DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/detail",
				Handler: post.GetPostDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/favorite/toggle",
				Handler: post.TogglePostFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/pin",
				Handler: post.PinPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/reaction/toggle",
				Handler: post.TogglePostReactionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/unpin",
				Handler: post.UnpinPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/update",
				Handler: post.UpdatePostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/profile/album/list",
				Handler: profile.GetProfileAlbumListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/featured/media/list",
				Handler: profile.GetProfileFeaturedMediaListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/featured/media/update",
				Handler: profile.UpdateProfileFeaturedMediaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/post/list/cursor",
				Handler: profile.GetProfilePostCursorListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
