// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	account "discover_world/internal/handler/account"
	admin "discover_world/internal/handler/admin"
	media "discover_world/internal/handler/media"
	overview "discover_world/internal/handler/overview"
	profile "discover_world/internal/handler/profile"
	"discover_world/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/login",
				Handler: account.LoginAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/register",
				Handler: account.RegisterAccountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/avatar/upload",
				Handler: account.UploadAccountAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/detail",
				Handler: account.DetailAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/update",
				Handler: account.UpdateAccountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/account/update",
					Handler: admin.AdminUpdateAccountHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/media/list",
					Handler: admin.GetAdminMediaAssetListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/media/list",
				Handler: media.GetMediaAssetListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/list/cursor",
				Handler: media.GetMediaAssetCursorListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/media/delete",
				Handler: media.DeleteMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/detail",
				Handler: media.GetMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/upload",
				Handler: media.UploadMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/upload/url",
				Handler: media.UploadMediaAssetByUrlHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/media/review",
					Handler: media.ReviewMediaAssetHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/overview/stats",
				Handler: overview.GetOverviewStatsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/profile/album/list",
				Handler: profile.GetProfileAlbumListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/featured/media/list",
				Handler: profile.GetProfileFeaturedMediaListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/post/list/cursor",
				Handler: profile.GetProfilePostCursorListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
