// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	account "discover_world/internal/handler/account"
	admin "discover_world/internal/handler/admin"
	feed "discover_world/internal/handler/feed"
	follow "discover_world/internal/handler/follow"
	forum "discover_world/internal/handler/forum"
	homepage "discover_world/internal/handler/homepage"
	media "discover_world/internal/handler/media"
	moderation "discover_world/internal/handler/moderation"
	notification "discover_world/internal/handler/notification"
	overview "discover_world/internal/handler/overview"
	post "discover_world/internal/handler/post"
	profile "discover_world/internal/handler/profile"
	search "discover_world/internal/handler/search"
	"discover_world/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LoginRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/account/login",
					Handler: account.LoginAccountHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RegisterRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/account/register",
					Handler: account.RegisterAccountHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/avatar/set",
				Handler: account.SetAccountAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/detail",
				Handler: account.DetailAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/logout",
				Handler: account.LogoutAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/update",
				Handler: account.UpdateAccountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/account/update",
					Handler: admin.AdminUpdateAccountHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/audit/operation/detail",
					Handler: admin.GetAdminOperationLogDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/audit/operation/list",
					Handler: admin.GetAdminOperationLogListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/homepage/featured/update",
					Handler: admin.UpdateHomepageFeaturedHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/homepage/hero/update",
					Handler: admin.UpdateHomepageHeroHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/media/list",
					Handler: admin.GetAdminMediaAssetListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/operation/content/feature",
					Handler: admin.FeatureAdminContentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/operation/content/unfeature",
					Handler: admin.UnfeatureAdminContentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/operation/dashboard",
					Handler: admin.GetAdminOperationDashboardHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/operation/tag/list",
					Handler: admin.GetAdminTagListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/operation/tag/merge",
					Handler: admin.MergeAdminTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/operation/tag/update",
					Handler: admin.UpdateAdminTagHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/feed/following/media/list/cursor",
				Handler: feed.GetFollowingMediaCursorListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/feed/following/post/list/cursor",
				Handler: feed.GetFollowingPostCursorListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/follow/cancel",
				Handler: follow.CancelFollowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow/create",
				Handler: follow.CreateFollowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow/follower/list",
				Handler: follow.GetFollowerListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow/following/list",
				Handler: follow.GetFollowingListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow/status",
				Handler: follow.GetFollowStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/forum/board/list",
				Handler: forum.GetForumBoardListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/forum/post/list/cursor",
				Handler: forum.GetForumPostCursorListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/forum/post/create",
				Handler: forum.CreateForumPostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/homepage/config",
				Handler: homepage.GetHomepageConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/media/list",
				Handler: media.GetMediaAssetListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/list/cursor",
				Handler: media.GetMediaAssetCursorListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/media/delete",
				Handler: media.DeleteMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/detail",
				Handler: media.GetMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/download",
				Handler: media.DownloadMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/reaction/toggle",
				Handler: media.ToggleMediaReactionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/upload/direct/complete",
				Handler: media.CompleteDirectMediaUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/upload/direct/init",
				Handler: media.InitDirectMediaUploadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/media/review",
					Handler: media.ReviewMediaAssetHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/moderation/report/create",
				Handler: moderation.CreateModerationReportHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/forum/post/lock",
					Handler: moderation.AdminLockForumPostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/forum/post/pin",
					Handler: moderation.AdminPinForumPostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/forum/post/unlock",
					Handler: moderation.AdminUnlockForumPostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/forum/post/unpin",
					Handler: moderation.AdminUnpinForumPostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/moderation/comment/hide",
					Handler: moderation.AdminHideCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/moderation/comment/restore",
					Handler: moderation.AdminRestoreCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/moderation/content/list",
					Handler: moderation.GetAdminContentListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/moderation/post/hide",
					Handler: moderation.AdminHidePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/moderation/post/restore",
					Handler: moderation.AdminRestorePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/moderation/report/detail",
					Handler: moderation.GetAdminModerationReportDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/moderation/report/list",
					Handler: moderation.GetAdminModerationReportListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/moderation/report/resolve",
					Handler: moderation.ResolveAdminModerationReportHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notification/list/cursor",
				Handler: notification.GetNotificationCursorListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/read",
				Handler: notification.MarkNotificationReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/read/all",
				Handler: notification.MarkAllNotificationsReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/unread/count",
				Handler: notification.GetUnreadNotificationCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/overview/stats",
				Handler: overview.GetOverviewStatsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/post/public/list/cursor",
				Handler: post.GetPublicPostCursorListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/post/comment/create",
				Handler: post.CreatePostCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/comment/list/cursor",
				Handler: post.GetPostCommentCursorListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/create",
				Handler: post.CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/delete",
				Handler: post.DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/detail",
				Handler: post.GetPostDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/favorite/toggle",
				Handler: post.TogglePostFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/pin",
				Handler: post.PinPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/reaction/toggle",
				Handler: post.TogglePostReactionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/unpin",
				Handler: post.UnpinPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/post/update",
				Handler: post.UpdatePostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/profile/album/list",
				Handler: profile.GetProfileAlbumListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/featured/media/list",
				Handler: profile.GetProfileFeaturedMediaListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/featured/media/update",
				Handler: profile.UpdateProfileFeaturedMediaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/post/list/cursor",
				Handler: profile.GetProfilePostCursorListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SearchRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/search",
					Handler: search.GlobalSearchHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
