// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package profile

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userProfileFieldNames          = builder.RawFieldNames(&UserProfile{})
	userProfileRows                = strings.Join(userProfileFieldNames, ",")
	userProfileRowsExpectAutoSet   = strings.Join(stringx.Remove(userProfileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userProfileRowsWithPlaceHolder = strings.Join(stringx.Remove(userProfileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userProfileModel interface {
		Insert(ctx context.Context, data *UserProfile) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserProfile, error)
		FindOneByUserId(ctx context.Context, userId uint64) (*UserProfile, error)
		Update(ctx context.Context, data *UserProfile) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserProfileModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserProfile struct {
		Id            uint64         `db:"id"`              // 用户资料ID
		UserId        uint64         `db:"user_id"`         // 用户ID
		Nickname      sql.NullString `db:"nickname"`        // 昵称
		AvatarAssetId sql.NullInt64  `db:"avatar_asset_id"` // 头像媒体资源ID
		Bio           sql.NullString `db:"bio"`             // 个人简介
		Gender        sql.NullString `db:"gender"`          // 性别，可选：male / female / unknown
		Birthday      sql.NullTime   `db:"birthday"`        // 生日
		Location      sql.NullString `db:"location"`        // 所在地
		BadgeJson     sql.NullString `db:"badge_json"`      // 徽章、成就、称号等
		ExtraJson     sql.NullString `db:"extra_json"`      // 扩展资料
		CreatedAt     time.Time      `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time      `db:"updated_at"`      // 更新时间
	}
)

func newUserProfileModel(conn sqlx.SqlConn) *defaultUserProfileModel {
	return &defaultUserProfileModel{
		conn:  conn,
		table: "`user_profile`",
	}
}

func (m *defaultUserProfileModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserProfileModel) FindOne(ctx context.Context, id uint64) (*UserProfile, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userProfileRows, m.table)
	var resp UserProfile
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfileModel) FindOneByUserId(ctx context.Context, userId uint64) (*UserProfile, error) {
	var resp UserProfile
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userProfileRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfileModel) Insert(ctx context.Context, data *UserProfile) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userProfileRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Nickname, data.AvatarAssetId, data.Bio, data.Gender, data.Birthday, data.Location, data.BadgeJson, data.ExtraJson)
	return ret, err
}

func (m *defaultUserProfileModel) Update(ctx context.Context, newData *UserProfile) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userProfileRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Nickname, newData.AvatarAssetId, newData.Bio, newData.Gender, newData.Birthday, newData.Location, newData.BadgeJson, newData.ExtraJson, newData.Id)
	return err
}

func (m *defaultUserProfileModel) tableName() string {
	return m.table
}
