// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package taxonomy

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tagFieldNames          = builder.RawFieldNames(&Tag{})
	tagRows                = strings.Join(tagFieldNames, ",")
	tagRowsExpectAutoSet   = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tagRowsWithPlaceHolder = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tagModel interface {
		Insert(ctx context.Context, data *Tag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Tag, error)
		FindOneByName(ctx context.Context, name string) (*Tag, error)
		FindOneBySlug(ctx context.Context, slug sql.NullString) (*Tag, error)
		Update(ctx context.Context, data *Tag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Tag struct {
		Id        uint64         `db:"id"`         // 标签ID
		Name      string         `db:"name"`       // 标签名称
		Slug      sql.NullString `db:"slug"`       // 标签唯一标识，适合URL使用
		TagType   string         `db:"tag_type"`   // 标签类型：normal普通 / system系统 / ai机器生成 / topic话题
		Status    int64          `db:"status"`     // 状态：1启用 / 0禁用
		CreatedAt time.Time      `db:"created_at"` // 创建时间
	}
)

func newTagModel(conn sqlx.SqlConn) *defaultTagModel {
	return &defaultTagModel{
		conn:  conn,
		table: "`tag`",
	}
}

func (m *defaultTagModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTagModel) FindOne(ctx context.Context, id uint64) (*Tag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tagRows, m.table)
	var resp Tag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) FindOneByName(ctx context.Context, name string) (*Tag, error) {
	var resp Tag
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", tagRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) FindOneBySlug(ctx context.Context, slug sql.NullString) (*Tag, error) {
	var resp Tag
	query := fmt.Sprintf("select %s from %s where `slug` = ? limit 1", tagRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, slug)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) Insert(ctx context.Context, data *Tag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, tagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Slug, data.TagType, data.Status)
	return ret, err
}

func (m *defaultTagModel) Update(ctx context.Context, newData *Tag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Slug, newData.TagType, newData.Status, newData.Id)
	return err
}

func (m *defaultTagModel) tableName() string {
	return m.table
}
