// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	assetLinkFieldNames          = builder.RawFieldNames(&AssetLink{})
	assetLinkRows                = strings.Join(assetLinkFieldNames, ",")
	assetLinkRowsExpectAutoSet   = strings.Join(stringx.Remove(assetLinkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	assetLinkRowsWithPlaceHolder = strings.Join(stringx.Remove(assetLinkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	assetLinkModel interface {
		Insert(ctx context.Context, data *AssetLink) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AssetLink, error)
		FindOneByOwnerTypeOwnerIdAssetIdLinkRole(ctx context.Context, ownerType string, ownerId uint64, assetId uint64, linkRole string) (*AssetLink, error)
		Update(ctx context.Context, data *AssetLink) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAssetLinkModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AssetLink struct {
		Id        uint64    `db:"id"`         // 媒体资源关联ID
		AssetId   uint64    `db:"asset_id"`   // 媒体资源ID
		OwnerType string    `db:"owner_type"` // 归属对象类型：post / album / user_profile 等
		OwnerId   uint64    `db:"owner_id"`   // 归属对象ID
		LinkRole  string    `db:"link_role"`  // 关联角色：attachment附件 / album_item相册项 / featured精选 / cover封面
		SortOrder int64     `db:"sort_order"` // 排序值，越小越靠前
		Status    int64     `db:"status"`     // 状态：1有效 / 0无效
		CreatedAt time.Time `db:"created_at"` // 创建时间
	}
)

func newAssetLinkModel(conn sqlx.SqlConn) *defaultAssetLinkModel {
	return &defaultAssetLinkModel{
		conn:  conn,
		table: "`asset_link`",
	}
}

func (m *defaultAssetLinkModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAssetLinkModel) FindOne(ctx context.Context, id uint64) (*AssetLink, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", assetLinkRows, m.table)
	var resp AssetLink
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAssetLinkModel) FindOneByOwnerTypeOwnerIdAssetIdLinkRole(ctx context.Context, ownerType string, ownerId uint64, assetId uint64, linkRole string) (*AssetLink, error) {
	var resp AssetLink
	query := fmt.Sprintf("select %s from %s where `owner_type` = ? and `owner_id` = ? and `asset_id` = ? and `link_role` = ? limit 1", assetLinkRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, ownerType, ownerId, assetId, linkRole)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAssetLinkModel) Insert(ctx context.Context, data *AssetLink) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, assetLinkRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AssetId, data.OwnerType, data.OwnerId, data.LinkRole, data.SortOrder, data.Status)
	return ret, err
}

func (m *defaultAssetLinkModel) Update(ctx context.Context, newData *AssetLink) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, assetLinkRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AssetId, newData.OwnerType, newData.OwnerId, newData.LinkRole, newData.SortOrder, newData.Status, newData.Id)
	return err
}

func (m *defaultAssetLinkModel) tableName() string {
	return m.table
}
