// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaObjectFieldNames          = builder.RawFieldNames(&MediaObject{})
	mediaObjectRows                = strings.Join(mediaObjectFieldNames, ",")
	mediaObjectRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaObjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaObjectRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaObjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	mediaObjectModel interface {
		Insert(ctx context.Context, data *MediaObject) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MediaObject, error)
		FindOneByBucketIdObjectKey(ctx context.Context, bucketId uint64, objectKey string) (*MediaObject, error)
		Update(ctx context.Context, data *MediaObject) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMediaObjectModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MediaObject struct {
		Id         uint64         `db:"id"`          // 媒体对象ID
		AssetId    uint64         `db:"asset_id"`    // 媒体资源ID
		BucketId   uint64         `db:"bucket_id"`   // 存储桶ID
		ObjectRole string         `db:"object_role"` // 对象角色：original原文件 / cover封面 / transcoded转码文件 / attachment附件
		ObjectKey  string         `db:"object_key"`  // 对象存储key，如 media/images/asset-1001/original.jpg
		StorageUri string         `db:"storage_uri"` // 统一存储URI，如 cos://bucket/key 或 s3://bucket/key
		MimeType   sql.NullString `db:"mime_type"`   // MIME类型，如 image/jpeg、video/mp4
		FileExt    sql.NullString `db:"file_ext"`    // 文件后缀，如 jpg / png / mp4 / webp
		FileSize   sql.NullInt64  `db:"file_size"`   // 文件大小，单位字节
		Width      sql.NullInt64  `db:"width"`       // 图片/视频宽度
		Height     sql.NullInt64  `db:"height"`      // 图片/视频高度
		DurationMs sql.NullInt64  `db:"duration_ms"` // 音视频时长，单位毫秒
		Checksum   sql.NullString `db:"checksum"`    // 文件校验值，如 sha256/md5
		Etag       sql.NullString `db:"etag"`        // 对象存储返回的 ETag
		AccessType string         `db:"access_type"` // 访问类型：public公开 / private私有
		Status     string         `db:"status"`      // 状态：active正常 / failed失败 / deleted已删除
		CreatedAt  time.Time      `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time      `db:"updated_at"`  // 更新时间
	}
)

func newMediaObjectModel(conn sqlx.SqlConn) *defaultMediaObjectModel {
	return &defaultMediaObjectModel{
		conn:  conn,
		table: "`media_object`",
	}
}

func (m *defaultMediaObjectModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMediaObjectModel) FindOne(ctx context.Context, id uint64) (*MediaObject, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaObjectRows, m.table)
	var resp MediaObject
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaObjectModel) FindOneByBucketIdObjectKey(ctx context.Context, bucketId uint64, objectKey string) (*MediaObject, error) {
	var resp MediaObject
	query := fmt.Sprintf("select %s from %s where `bucket_id` = ? and `object_key` = ? limit 1", mediaObjectRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, bucketId, objectKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaObjectModel) Insert(ctx context.Context, data *MediaObject) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mediaObjectRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AssetId, data.BucketId, data.ObjectRole, data.ObjectKey, data.StorageUri, data.MimeType, data.FileExt, data.FileSize, data.Width, data.Height, data.DurationMs, data.Checksum, data.Etag, data.AccessType, data.Status)
	return ret, err
}

func (m *defaultMediaObjectModel) Update(ctx context.Context, newData *MediaObject) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mediaObjectRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AssetId, newData.BucketId, newData.ObjectRole, newData.ObjectKey, newData.StorageUri, newData.MimeType, newData.FileExt, newData.FileSize, newData.Width, newData.Height, newData.DurationMs, newData.Checksum, newData.Etag, newData.AccessType, newData.Status, newData.Id)
	return err
}

func (m *defaultMediaObjectModel) tableName() string {
	return m.table
}
