// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaVariantRuleFieldNames          = builder.RawFieldNames(&MediaVariantRule{})
	mediaVariantRuleRows                = strings.Join(mediaVariantRuleFieldNames, ",")
	mediaVariantRuleRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaVariantRuleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaVariantRuleRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaVariantRuleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	mediaVariantRuleModel interface {
		Insert(ctx context.Context, data *MediaVariantRule) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MediaVariantRule, error)
		FindOneByCodeProviderTypeMediaType(ctx context.Context, code string, providerType string, mediaType string) (*MediaVariantRule, error)
		Update(ctx context.Context, data *MediaVariantRule) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMediaVariantRuleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MediaVariantRule struct {
		Id            uint64        `db:"id"`             // 媒体版本规则ID
		Code          string        `db:"code"`           // 版本编码：thumbnail / preview / detail / avatar
		Name          string        `db:"name"`           // 版本名称
		MediaType     string        `db:"media_type"`     // 媒体类型：image / video
		ProviderType  string        `db:"provider_type"`  // 存储服务类型：cos / oss / s3 / minio
		ProcessParams string        `db:"process_params"` // 处理参数，如 imageMogr2/thumbnail/400x
		Width         sql.NullInt64 `db:"width"`          // 目标宽度
		Height        sql.NullInt64 `db:"height"`         // 目标高度
		Status        int64         `db:"status"`         // 状态：1启用 / 0禁用
		CreatedAt     time.Time     `db:"created_at"`     // 创建时间
		UpdatedAt     time.Time     `db:"updated_at"`     // 更新时间
	}
)

func newMediaVariantRuleModel(conn sqlx.SqlConn) *defaultMediaVariantRuleModel {
	return &defaultMediaVariantRuleModel{
		conn:  conn,
		table: "`media_variant_rule`",
	}
}

func (m *defaultMediaVariantRuleModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMediaVariantRuleModel) FindOne(ctx context.Context, id uint64) (*MediaVariantRule, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaVariantRuleRows, m.table)
	var resp MediaVariantRule
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaVariantRuleModel) FindOneByCodeProviderTypeMediaType(ctx context.Context, code string, providerType string, mediaType string) (*MediaVariantRule, error) {
	var resp MediaVariantRule
	query := fmt.Sprintf("select %s from %s where `code` = ? and `provider_type` = ? and `media_type` = ? limit 1", mediaVariantRuleRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code, providerType, mediaType)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaVariantRuleModel) Insert(ctx context.Context, data *MediaVariantRule) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, mediaVariantRuleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Name, data.MediaType, data.ProviderType, data.ProcessParams, data.Width, data.Height, data.Status)
	return ret, err
}

func (m *defaultMediaVariantRuleModel) Update(ctx context.Context, newData *MediaVariantRule) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mediaVariantRuleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.Name, newData.MediaType, newData.ProviderType, newData.ProcessParams, newData.Width, newData.Height, newData.Status, newData.Id)
	return err
}

func (m *defaultMediaVariantRuleModel) tableName() string {
	return m.table
}
