// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaUploadSessionFieldNames          = builder.RawFieldNames(&MediaUploadSession{})
	mediaUploadSessionRows                = strings.Join(mediaUploadSessionFieldNames, ",")
	mediaUploadSessionRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaUploadSessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaUploadSessionRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaUploadSessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	mediaUploadSessionModel interface {
		Insert(ctx context.Context, data *MediaUploadSession) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MediaUploadSession, error)
		Update(ctx context.Context, data *MediaUploadSession) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMediaUploadSessionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MediaUploadSession struct {
		Id               uint64         `db:"id"`                // 上传会话ID
		UserId           uint64         `db:"user_id"`           // 上传用户ID
		AssetId          sql.NullInt64  `db:"asset_id"`          // 关联媒体资源ID，可在上传完成后绑定
		ProviderId       sql.NullInt64  `db:"provider_id"`       // 存储服务商ID
		BucketId         sql.NullInt64  `db:"bucket_id"`         // 存储桶ID
		UploadType       string         `db:"upload_type"`       // 上传类型：direct直传 / multipart分片 / server_proxy服务端代理
		UploadId         sql.NullString `db:"upload_id"`         // 对象存储分片上传ID
		ObjectKey        string         `db:"object_key"`        // 目标对象key
		OriginalFilename sql.NullString `db:"original_filename"` // 原始文件名
		MimeType         sql.NullString `db:"mime_type"`         // MIME类型
		FileSize         sql.NullInt64  `db:"file_size"`         // 文件大小，单位字节
		Status           string         `db:"status"`            // 状态：created已创建 / uploading上传中 / completed已完成 / failed失败 / expired已过期
		ExpireAt         sql.NullTime   `db:"expire_at"`         // 上传凭证或会话过期时间
		CallbackPayload  sql.NullString `db:"callback_payload"`  // 对象存储回调数据
		ExtraJson        sql.NullString `db:"extra_json"`        // 扩展字段
		CreatedAt        time.Time      `db:"created_at"`        // 创建时间
		UpdatedAt        time.Time      `db:"updated_at"`        // 更新时间
	}
)

func newMediaUploadSessionModel(conn sqlx.SqlConn) *defaultMediaUploadSessionModel {
	return &defaultMediaUploadSessionModel{
		conn:  conn,
		table: "`media_upload_session`",
	}
}

func (m *defaultMediaUploadSessionModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMediaUploadSessionModel) FindOne(ctx context.Context, id uint64) (*MediaUploadSession, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaUploadSessionRows, m.table)
	var resp MediaUploadSession
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaUploadSessionModel) Insert(ctx context.Context, data *MediaUploadSession) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mediaUploadSessionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AssetId, data.ProviderId, data.BucketId, data.UploadType, data.UploadId, data.ObjectKey, data.OriginalFilename, data.MimeType, data.FileSize, data.Status, data.ExpireAt, data.CallbackPayload, data.ExtraJson)
	return ret, err
}

func (m *defaultMediaUploadSessionModel) Update(ctx context.Context, data *MediaUploadSession) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mediaUploadSessionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AssetId, data.ProviderId, data.BucketId, data.UploadType, data.UploadId, data.ObjectKey, data.OriginalFilename, data.MimeType, data.FileSize, data.Status, data.ExpireAt, data.CallbackPayload, data.ExtraJson, data.Id)
	return err
}

func (m *defaultMediaUploadSessionModel) tableName() string {
	return m.table
}
