// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shareLinkFieldNames          = builder.RawFieldNames(&ShareLink{})
	shareLinkRows                = strings.Join(shareLinkFieldNames, ",")
	shareLinkRowsExpectAutoSet   = strings.Join(stringx.Remove(shareLinkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shareLinkRowsWithPlaceHolder = strings.Join(stringx.Remove(shareLinkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shareLinkModel interface {
		Insert(ctx context.Context, data *ShareLink) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShareLink, error)
		FindOneByToken(ctx context.Context, token string) (*ShareLink, error)
		Update(ctx context.Context, data *ShareLink) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShareLinkModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShareLink struct {
		Id             uint64        `db:"id"`               // 分享链接ID
		UserId         uint64        `db:"user_id"`          // 创建分享的用户ID
		TargetType     string        `db:"target_type"`      // 目标类型：media_asset / post / album / user_profile
		TargetId       uint64        `db:"target_id"`        // 目标对象ID
		Token          string        `db:"token"`            // 分享令牌，URL中使用
		PermissionType string        `db:"permission_type"`  // 权限类型：view预览 / download下载
		ExpireAt       sql.NullTime  `db:"expire_at"`        // 过期时间，NULL表示不过期
		MaxAccessCount sql.NullInt64 `db:"max_access_count"` // 最大访问次数，NULL表示不限
		AccessCount    uint64        `db:"access_count"`     // 已访问次数
		Status         int64         `db:"status"`           // 状态：1启用 / 0禁用
		CreatedAt      time.Time     `db:"created_at"`       // 创建时间
	}
)

func newShareLinkModel(conn sqlx.SqlConn) *defaultShareLinkModel {
	return &defaultShareLinkModel{
		conn:  conn,
		table: "`share_link`",
	}
}

func (m *defaultShareLinkModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShareLinkModel) FindOne(ctx context.Context, id uint64) (*ShareLink, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shareLinkRows, m.table)
	var resp ShareLink
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShareLinkModel) FindOneByToken(ctx context.Context, token string) (*ShareLink, error) {
	var resp ShareLink
	query := fmt.Sprintf("select %s from %s where `token` = ? limit 1", shareLinkRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, token)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShareLinkModel) Insert(ctx context.Context, data *ShareLink) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shareLinkRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TargetType, data.TargetId, data.Token, data.PermissionType, data.ExpireAt, data.MaxAccessCount, data.AccessCount, data.Status)
	return ret, err
}

func (m *defaultShareLinkModel) Update(ctx context.Context, newData *ShareLink) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shareLinkRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.TargetType, newData.TargetId, newData.Token, newData.PermissionType, newData.ExpireAt, newData.MaxAccessCount, newData.AccessCount, newData.Status, newData.Id)
	return err
}

func (m *defaultShareLinkModel) tableName() string {
	return m.table
}
