// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	storageBucketFieldNames          = builder.RawFieldNames(&StorageBucket{})
	storageBucketRows                = strings.Join(storageBucketFieldNames, ",")
	storageBucketRowsExpectAutoSet   = strings.Join(stringx.Remove(storageBucketFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	storageBucketRowsWithPlaceHolder = strings.Join(stringx.Remove(storageBucketFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	storageBucketModel interface {
		Insert(ctx context.Context, data *StorageBucket) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*StorageBucket, error)
		FindOneByProviderIdBucketName(ctx context.Context, providerId uint64, bucketName string) (*StorageBucket, error)
		Update(ctx context.Context, data *StorageBucket) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultStorageBucketModel struct {
		conn  sqlx.SqlConn
		table string
	}

	StorageBucket struct {
		Id           uint64         `db:"id"`            // 存储桶ID
		ProviderId   uint64         `db:"provider_id"`   // 存储服务商ID
		BucketName   string         `db:"bucket_name"`   // 桶名称
		BucketRegion sql.NullString `db:"bucket_region"` // 桶所在地域
		Endpoint     sql.NullString `db:"endpoint"`      // 桶访问端点
		CdnDomain    sql.NullString `db:"cdn_domain"`    // CDN域名
		BasePath     sql.NullString `db:"base_path"`     // 基础路径，如 media/images
		AccessType   string         `db:"access_type"`   // 访问类型：public公开 / private私有
		UsageType    string         `db:"usage_type"`    // 用途：media普通媒体 / avatar头像 / video视频 / temp临时 / backup备份
		IsDefault    int64          `db:"is_default"`    // 是否默认桶：1是 / 0否
		Status       int64          `db:"status"`        // 状态：1启用 / 0禁用
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
	}
)

func newStorageBucketModel(conn sqlx.SqlConn) *defaultStorageBucketModel {
	return &defaultStorageBucketModel{
		conn:  conn,
		table: "`storage_bucket`",
	}
}

func (m *defaultStorageBucketModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStorageBucketModel) FindOne(ctx context.Context, id uint64) (*StorageBucket, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", storageBucketRows, m.table)
	var resp StorageBucket
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStorageBucketModel) FindOneByProviderIdBucketName(ctx context.Context, providerId uint64, bucketName string) (*StorageBucket, error) {
	var resp StorageBucket
	query := fmt.Sprintf("select %s from %s where `provider_id` = ? and `bucket_name` = ? limit 1", storageBucketRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, providerId, bucketName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStorageBucketModel) Insert(ctx context.Context, data *StorageBucket) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, storageBucketRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProviderId, data.BucketName, data.BucketRegion, data.Endpoint, data.CdnDomain, data.BasePath, data.AccessType, data.UsageType, data.IsDefault, data.Status)
	return ret, err
}

func (m *defaultStorageBucketModel) Update(ctx context.Context, newData *StorageBucket) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, storageBucketRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ProviderId, newData.BucketName, newData.BucketRegion, newData.Endpoint, newData.CdnDomain, newData.BasePath, newData.AccessType, newData.UsageType, newData.IsDefault, newData.Status, newData.Id)
	return err
}

func (m *defaultStorageBucketModel) tableName() string {
	return m.table
}
