// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	storageProviderFieldNames          = builder.RawFieldNames(&StorageProvider{})
	storageProviderRows                = strings.Join(storageProviderFieldNames, ",")
	storageProviderRowsExpectAutoSet   = strings.Join(stringx.Remove(storageProviderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	storageProviderRowsWithPlaceHolder = strings.Join(stringx.Remove(storageProviderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	storageProviderModel interface {
		Insert(ctx context.Context, data *StorageProvider) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*StorageProvider, error)
		FindOneByCode(ctx context.Context, code string) (*StorageProvider, error)
		Update(ctx context.Context, data *StorageProvider) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultStorageProviderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	StorageProvider struct {
		Id           uint64         `db:"id"`            // 存储服务商ID
		Code         string         `db:"code"`          // 服务商编码，如 cos / oss / s3 / minio / local
		Name         string         `db:"name"`          // 服务商名称，如 腾讯云COS
		ProviderType string         `db:"provider_type"` // 服务商类型：cos / oss / s3 / minio / local
		Endpoint     sql.NullString `db:"endpoint"`      // 服务端点
		Region       sql.NullString `db:"region"`        // 默认地域
		ConfigJson   sql.NullString `db:"config_json"`   // 非敏感配置，如 pathStyle、是否启用CDN等
		SecretRef    sql.NullString `db:"secret_ref"`    // 密钥引用，不建议直接存密钥明文
		Status       int64          `db:"status"`        // 状态：1启用 / 0禁用
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
	}
)

func newStorageProviderModel(conn sqlx.SqlConn) *defaultStorageProviderModel {
	return &defaultStorageProviderModel{
		conn:  conn,
		table: "`storage_provider`",
	}
}

func (m *defaultStorageProviderModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStorageProviderModel) FindOne(ctx context.Context, id uint64) (*StorageProvider, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", storageProviderRows, m.table)
	var resp StorageProvider
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStorageProviderModel) FindOneByCode(ctx context.Context, code string) (*StorageProvider, error) {
	var resp StorageProvider
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", storageProviderRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStorageProviderModel) Insert(ctx context.Context, data *StorageProvider) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, storageProviderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Name, data.ProviderType, data.Endpoint, data.Region, data.ConfigJson, data.SecretRef, data.Status)
	return ret, err
}

func (m *defaultStorageProviderModel) Update(ctx context.Context, newData *StorageProvider) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, storageProviderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.Name, newData.ProviderType, newData.Endpoint, newData.Region, newData.ConfigJson, newData.SecretRef, newData.Status, newData.Id)
	return err
}

func (m *defaultStorageProviderModel) tableName() string {
	return m.table
}
